// <auto-generated />
using System;
using MangoFood.Service.ProductAPI.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MangoFood.Service.ProductAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250120072954_createProduct")]
    partial class createProduct
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MangoFood.Service.ProductAPI.Data.Entities.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a973c64d-897a-43e3-a106-24c0e953af6f"),
                            CategoryName = "Pizza",
                            Description = "Classic Italian pizza with fresh mozzarella and basil.",
                            ImageUrl = "https://i.pinimg.com/736x/d4/bf/d5/d4bfd54c3f5f672af5be24513e12902f.jpg",
                            Name = "Pizza Margherita",
                            Price = 9.9900000000000002
                        },
                        new
                        {
                            Id = new Guid("e0d524ec-bfc8-4391-bb94-29a4f92cfdd7"),
                            CategoryName = "Pasta",
                            Description = "Traditional pasta with creamy egg sauce, pancetta, and Parmesan.",
                            ImageUrl = "https://i.pinimg.com/736x/32/98/80/329880050b7fded253ca69bd31cd84d8.jpg",
                            Name = "Spaghetti Carbonara",
                            Price = 12.99
                        },
                        new
                        {
                            Id = new Guid("1bbf06b4-8438-4daa-8470-67e6fe7546a2"),
                            CategoryName = "Salad",
                            Description = "Fresh romaine lettuce, croutons, Parmesan cheese, and Caesar dressing.",
                            ImageUrl = "https://i.pinimg.com/736x/68/eb/9e/68eb9eac17e7649a84ab3b485e01a843.jpg",
                            Name = "Caesar Salad",
                            Price = 7.4900000000000002
                        },
                        new
                        {
                            Id = new Guid("4f381098-6e23-4158-b094-8808b7d46b2c"),
                            CategoryName = "Burger",
                            Description = "Juicy beef patty with melted cheese, lettuce, tomato, and pickles.",
                            ImageUrl = "https://i.pinimg.com/736x/8b/36/9f/8b369fefca44952ef36cc09f830c00e7.jpg",
                            Name = "Cheeseburger",
                            Price = 8.9900000000000002
                        },
                        new
                        {
                            Id = new Guid("ac2dafc5-2706-4b4d-9bf0-e364f403aa36"),
                            CategoryName = "Beverages",
                            Description = "Refreshing mango smoothie made with ripe mangoes and yogurt.",
                            ImageUrl = "https://i.pinimg.com/736x/d2/2c/49/d22c49a7b5309f97eb57e0dda6304a1b.jpg",
                            Name = "Mango Smoothie",
                            Price = 4.9900000000000002
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
